version: "3"

services:
  node:
    build: ./node
    ports:
      - "3000:3000"
    depends_on:
      - fastapi

  fastapi:
    build:
      context: ./fastapi
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"