"""add verification and balance

Revision ID: 05ca38950b6b
Revises: 6cc24e8d777f
Create Date: 2026-03-16 07:49:59.771279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '05ca38950b6b'
down_revision: Union[str, Sequence[str], None] = '6cc24e8d777f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compeer', sa.Column('signup_verification', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('compeer', sa.Column('verified', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('compeer', sa.Column('balance', sa.Float(), server_default=sa.text('0.0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('compeer', 'balance')
    op.drop_column('compeer', 'verified')
    op.drop_column('compeer', 'signup_verification')
    # ### end Alembic commands ###
